CUDA_VISIBLE_DEVICES=0,1,2,3 python  main.py \
            --gpu           $1    \
            --eval_epoch    1  \
            --only_test     0   \
            --model_name    UMAEA \
            --data_choice   $2 \
            --data_split    $3 \
            --data_rate     $4 \
            --epoch         50 \
            --lr            4e-3  \
            --hidden_units  "300,300,300" \
            --save_model    0 \
            --batch_size    3500 \
	    --csls          \
	    --csls_k        3 \
            --distance      2 \
	    --random_seed   3408 \
            --exp_name      UMAEA_00_R$5 \
            --exp_id        V1_$4 \
            --workers       12 \
            --accumulation_steps 1 \
            --scheduler     cos \
            --attr_dim      300     \
            --img_dim       300     \
            --name_dim      300     \
            --char_dim      300     \
            --hidden_size   300     \
            --intermediate_size 400 \
            --tau           0.1     \
            --structure_encoder "gat" \
            --num_attention_heads 1 \
            --num_hidden_layers 1 \
            --use_surface   0     \
            --use_intermediate 1   \
            --awloss 1 \
            --stage 0 \
            --adapt vae \
            --ratio $5 \
            --stage_epoch "250,0,0" \
            --il_stage_epoch "250,0,0" \
            --il            \
	    --il_start      250 \
            --semi_learn_step 5 \
	    --csls          \
	    --csls_k        3 \
            
